name: React CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install
      
    - name: Run Tests
      run: npm test -- --watchAll=false # Ye step ab GitHub pe test chalayega

    - name: Build Project
      run: npm run build
    - name: Deploy 
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: build # Ye wahi folder hai jo Build step ne banaya
          branch: gh-pages
